strongHome:
  list_services:
    - Radius
    - OwnCloud
    - Email
    - VoIP
  list_users:
    - user: admin
      admin: yes
      password: Asdfaksdnjasdnjasnjdas
      first_name: Leticia
      last_name: Perez
      services:
        - Radius
        - OwnCloud
        - Email
        - VoIP
    - user: test1
      password: skdjaskjdasjk
      first_name: Juan
      last_name: Gonzalez
      services:
        - Radius
    - user: test2
      password: Asasdddadaddfaksdnjasdnjasnjdas
      first_name: Pedro
      last_name: Marín
      services:
        - Radius
        - VoIP
    - user: test3
      password: 1234567890abc
      first_name: Pedro
      last_name: Marín
      services:
        - VoIP
